### ISSUE TITLE
cBioPortal linkout changed

### ISSUE THREAD

**Issue by ChrisWakefield** [MD-Anderson-Bioinformatics/NG-CHM#235]
cbio, cBioPortal changed their links to access internal pages.  Where we used to link to http://www.cbioportal.org/ln?cancer_study_id=...
it seems it needs to change to links of the form: https://www.cbioportal.org/results?case_set_id=blca_tcga_all&cancer_study_list=blca_tcga&gene_list=ERG

We assume case_set_id should always be the cancer_study code + "_all"

**Comment by jmelott** [comment]
Still present 2022 02 07.

**Comment by jmelott** [comment]
Failed when testing.

If linkouts pane is open, also is incorrectly trying to use it instead of opening a new tab.
Get message error in console: 
Refused to display 'http://www.cbioportal.org/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.


If linkouts pane is not open when selected, 
cbioportal link always results in blank screen.
Link displayed in URL when selected is http://www.cbioportal.org/ln?cancer_study_id=brca_tcga_pub&gene_list=BRCA1
Error message in console for cbioportal page.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at main.app.js?20220406-2053:2:1831951
    at c (main.app.js?20220406-2053:2:3137740)
    at Generator._invoke (main.app.js?20220406-2053:2:3137528)
    at Generator.next (main.app.js?20220406-2053:2:3138165)
    at a (main.app.js?20220406-2053:2:1829397)

**Comment by ChrisWakefield** [comment]
@jmelott  You are not using the right version of custom.js, so the test is invalid.  As described in the comment from Jan. 19, links to cBio's "/ln" were obsolete.  The change replaced that with a link to the "/results" format.  (Is docker's -v unintentionally replacing the source of custom.js?)

That is separate from "Refused to display 'http://www.cbioportal.org/' in a frame because it set 'X-Frame-Options' to 'sameorigin'."  If cBio disallows what we are trying to do, we may be stuck.  You are correct that this could be opened in a separate tab, but the (new) design is that linkouts will always open in the linkouts panel when there is one.  Was there a decision to change/fix how this worked?

**Comment by jmelott** [comment]
I'm not familiar enough with the code in custom.js to know the exact changes needed, but the there is some way to set up an individual plugin to always open in a new frame instead of trying to use the linkouts.  The bioGPS and MaveDB plugins always open in a new tab instead of trying to use the linkout pane.

Since the custom.js isn't automatically built into the system, I was testing on the production system.  Have the changes been made there already, or did you want me to try modifying the custom.js on udev7 and test there?

**Comment by ChrisWakefield** [comment]
Based on comparing custom.js just now, the current release version has the changes suggested above.  The links now go to "/results" and openUrl is passed {noframe: true}, so the issue should be addressed.  I'm still hesitant to close the issue without having been retested by @jmelott .

**Comment by jmelott** [comment]
Verified working on production 2022_11_30.
