### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by davidchristiany** [MD-Anderson-Bioinformatics/NG-CHM#3]
Hi, 

I am trying to install and use "Next-Generation Clustered Heat Map (NG-CHM) Viewer" on a galaxy instance. I followed all steps of the tutorial video : 
- install from toolshed (2018-02-08)
- move mda_heatmap_viz.zip to galaxy/config/plugins/visualization and unzip it
- restart galaxy

I used the 400x400.txt file included in the tool directory and default settings to test.
I got this error : 

`Fatal error:`
`Exception in thread "main" java.lang.UnsupportedClassVersionError: mda/ngchm/datagenerator/GalaxyMapGen : Unsupported major.minor version 52.0`
`at java.lang.ClassLoader.defineClass1(Native Method)`
`at java.lang.ClassLoader.defineClass(ClassLoader.java:803)`
`at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)`
`at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)`
`at java.net.URLClassLoader.access$100(URLClassLoader.java:64)`
`at java.net.URLClassLoader$1.run(URLClassLoader.java:354)`
`at java.net.URLClassLoader$1.run(URLClassLoader.java:348)`
`at java.security.AccessController.doPrivileged(Native Method)`
`at java.net.URLClassLoader.findClass(URLClassLoader.java:347)`
`at java.lang.ClassLoader.loadClass(ClassLoader.java:425)`
`at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)`
`at java.lang.ClassLoader.loadClass(ClassLoader.java:358)`
`at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)`
`WARNING:galaxy.model:Datatype class not found for extension 'ngchm'`
`WARNING:galaxy.model:Datatype class not found for extension 'ngchm'`
`WARNING:galaxy.model:Datatype class not found for extension 'ngchm'`
`WARNING:galaxy.model:Datatype class not found for extension 'ngchm'`
`WARNING:galaxy.model:Datatype class not found for extension 'ngchm'`

I running this tool in galaxy 18.05.

I also try to use the same version as the tutorial (the first one).
the job seems to end normally but when I click on the "charts" button and then to NG-CHM heat map viewer (only option) I got a blank page with a link at the bottom left : 
http://insilico.us.com/

Can you help ?

**Comment by bmbroom** [comment]
Mike,

Can you help?

Thanks,
Bradley.

**Comment by bob-insilico** [comment]
David, 
We will look into this and get back to you as soon as we have something.
Sincerely,
Bob

**Comment by bob-insilico** [comment]
Good morning David,
The issue is your machine needs to be updated to use Java 1.8.   1.8 version has been out for a several years.
I am going to look into adding a Galaxy xml requirements statement in the tool xml and see if that will notify users in a more friendly way of this requirement.

If there is anything else regarding this issue please let us know.
And thank you for trying our tool and giving us feedback.

Cheers,
Bob Brown

**Comment by davidchristiany** [comment]
Hi,

I added java.jdk as a requirement : 
`<requirement type="package" version="8.0.112">java-jdk</requirement>`

Now I have another issue telling me that there's no datatype class for extension 'ngchm' : 

```
java.lang.NumberFormatException: For input string: "-1,2104"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at mda.ngchm.datagenerator.HeatmapDataGenerator.createTnHeatmapImg(Unknown Source)
	at mda.ngchm.datagenerator.HeatmapDataGenerator.processHeatMap(Unknown Source)
	at mda.ngchm.datagenerator.GalaxyMapGen.performStandardMapGeneration(Unknown Source)
	at mda.ngchm.datagenerator.GalaxyMapGen.main(Unknown Source)
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
```

I got this error while testing with an example dataset (400x400.txt) found in the directory tool 
(md-anderson-bioinformatics/heat_map_creation/58437af2d675/heat_map_creation)

Apparently this type of issue may occur after the last upate of galaxy.
Do I need to manually add this datatype to galaxy ? 
(https://galaxyproject.org/admin/datatypes/adding-datatypes/)

**Comment by bob-insilico** [comment]
Good morning,That is my understanding from the Galaxy staff, of the fix for requiring Java 8, that is needed for the ngchm class.    We are in the process of validating this ourselves, but were upgrading some tools at the same time.  So I can have a better answer next week.  Thank you for your persistence and patience.Sincerely,Bob BrownOn October 26, 2018 at 4:55 AM David Christiany <notifications@github.com> wrote:  Hi,I added java.jdk as a requirement : <requirement type="package" version="8.0.112">java-jdk</requirement>Now I have another issue telling me that there's no datatype class for extension 'ngchm' :java.lang.NumberFormatException: For input string: "-1,2104"
 at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
 at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
 at java.lang.Float.parseFloat(Float.java:451)
 at mda.ngchm.datagenerator.HeatmapDataGenerator.createTnHeatmapImg(Unknown Source)
 at mda.ngchm.datagenerator.HeatmapDataGenerator.processHeatMap(Unknown Source)
 at mda.ngchm.datagenerator.GalaxyMapGen.performStandardMapGeneration(Unknown Source)
 at mda.ngchm.datagenerator.GalaxyMapGen.main(Unknown Source)
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
I got this error while testing with an example dataset (400x400.txt) found in the directory tool (md-anderson-bioinformatics/heat_map_creation/58437af2d675/heat_map_creation)Apparently this type of issue may occur after the last upate of galaxy. Do I need to manually add this datatype to galaxy ? (https://galaxyproject.org/admin/datatypes/adding-datatypes/)—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by bob-insilico** [comment]
Good morning David,What country are you in.   We did not account for the European (and other regions?) swapping decimal points (periods) for commas in the numbers.Sincerely,BobOn October 26, 2018 at 4:55 AM David Christiany <notifications@github.com> wrote:  Hi,I added java.jdk as a requirement : <requirement type="package" version="8.0.112">java-jdk</requirement>Now I have another issue telling me that there's no datatype class for extension 'ngchm' :java.lang.NumberFormatException: For input string: "-1,2104"
 at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
 at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
 at java.lang.Float.parseFloat(Float.java:451)
 at mda.ngchm.datagenerator.HeatmapDataGenerator.createTnHeatmapImg(Unknown Source)
 at mda.ngchm.datagenerator.HeatmapDataGenerator.processHeatMap(Unknown Source)
 at mda.ngchm.datagenerator.GalaxyMapGen.performStandardMapGeneration(Unknown Source)
 at mda.ngchm.datagenerator.GalaxyMapGen.main(Unknown Source)
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
WARNING:galaxy.model:Datatype class not found for extension 'ngchm'
I got this error while testing with an example dataset (400x400.txt) found in the directory tool (md-anderson-bioinformatics/heat_map_creation/58437af2d675/heat_map_creation)Apparently this type of issue may occur after the last upate of galaxy. Do I need to manually add this datatype to galaxy ? (https://galaxyproject.org/admin/datatypes/adding-datatypes/)—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
