### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Caro-Ca** [MD-Anderson-Bioinformatics/NG-CHM#52]
[diagnostics.log](https://github.com/MD-Anderson-Bioinformatics/NG-CHM/files/5215037/diagnostics.log)
Dear, 
here I attach the log file of my issue. 
I installed docker for mac version 10.14.6, R version is  4.0.2 and Java 14.0.2 2020-07-14

I hope you could help me out. 
Thank you in advance.

**Comment by ChrisWakefield** [comment]
@Caro-Ca I don't understand what the issue is.  What is it you are trying to do, and what is the problem you are seeing?
Your diagnostics.log contains a line that reads:
"Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
so you either do not have docker running, or do not have permissions to access it.  That is not an NGCHM issue.
Also, I have installed "Docker Community Edition" Version 17.12.0 on my Mac, and it is not even the latest Docker.  The version you mention (10.14.6) sounds quite dated.

**Comment by ChrisWakefield** [comment]
@Caro-Ca There is no docker for mac version 10.14.6 mentioned on https://docs.docker.com/docker-for-mac/release-notes/

**Comment by bmbroom** [comment]
Not clear what the problem was.  No clarification from OP for > 6 months.
